### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by AdmiralRazorbeard** [Angelmaneuver/command-launcher#1]
This extension is amazing, only 14 downloads wtf.
I use many extensions so this is very handy to access many commands. Even more powerful when combined with the multi-command extension.

Yeah this is not an "issue" but I had to say it

**Comment by AdmiralRazorbeard** [comment]
I did find a very minor issue 
![image](https://user-images.githubusercontent.com/6703087/175093241-e724f4bd-b1b9-4b95-a7db-d954880ac9a5.png)
launcher instead of lanucher

**Comment by Angelmaneuver** [comment]
Hi AdmiralRazorbeard.

Thanks for the compliment.

I also think this extension is a tour de force, but it's a pity that there are so many command extensions already released that don't seem to catch people's attention.

Still, I am glad that there are people like you who are pleased with it.

**Comment by AdmiralRazorbeard** [comment]
I always wanted to write an article about hidden gems of Vscode, yours is definitely top 3. I hope I will be able to do that soon
